### ISSUE TITLE
Importer interface 🚚

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1595]
## Definitions of key terminology
* **IMPORTING** in Zetkin is the action of creating/updating a lot of person records in a single API call. In Gen2 it used the "imports" API and in Gen3 (Core2) it will be using a new (general-purpose) bulk API.

## Target audience
These are some roles that will most likely use this feature:

* **ADMINS** who need to import their full or partial membership to Zetkin for organizing
* **ORGANIZERS** who have additional data about people outside of Zetkin and want to complement records in Zetkin with additional information
* **COMMUNICATORS** who have exported a list and sent an email, and then want to import back the data to tag which ones read the email

## Requirements (job stories)
Below are job stories that describe the requirements for this feature.

* When I configure a new import I want continuous feedback on what columns are mandatory to map, so that I know when an import is possible to be performed
* When I import data from excel, I want Zetkin to filter out excel internal data columns from the columns I am presented with, so that I don’t have to try to understand if it is relevant data
* When I import a spreadsheet file from another system, I want to configure which columns maps which fields, so that I can use any file formatting without having to prepare the file for the Zetkin import
* When I import, I want an easy way to add people to their respective sub-organizations, so that they can be organized
* When I’ve successfully performed an import I want feedback on added/changed/updated persons and fields, so that I’m confident of what has changed in the Zetkin database of people
* When I get an error during import I want to know what I did wrong so I can correct my mistake 
* When I’m importing a large dataset which can’t be processed right away I want Zetkin to tell me when I can expect it to be done so that I don’t have to spend time actively monitoring it
* When I import a list with many people I want to be able to skim through the whole list so I know everyone got the tags I expect
* When I’m mapping data from a field in a file during import to tag, I want enough information about how tags will be applied, so that I can feel confident that the tag will be applied to the right people
* When I import information, I want a sense of overview, so that I’m not overwhelmed by the amount/ scale of information
* When I work on an import, I want to retain a bird’s eye preview of what the import will do in its current configuration, so that I don’t lose control of what data will be imported
* When I don’t understand what external ID is for, I want Zetkin to explain to me what it is and why it is important, so that I don’t worry about using it the wrong way
* When I think I’m ready to perform an import, I want to be warned of any possible misconfigurations ahead of performing it, so that bad data in Zetkin can be minimized
* When I import updated data on existing persons, I want to be sure that it is replacing the old data of existing persons and not creating duplicate persons, so that I won’t mess up the database
* When I import data on new persons, I want to be sure that it is being added to the database and not overwriting something else, so that I won’t mess up the database
* When I configure an import to update person information such as email address, I want to know how much this import affects the existing database, so that I can feel that I’m in control
* When I’m mapping a list with many people I want to be able to quickly see any unaffected people, so I know everyone got associated to the data I want and expect

### File upload
Files can be dropped or selected using the device file browser.
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/5e02fbf4-c3fe-443a-8381-adcd6a8e0274)

### Import configuration
There are settings and configuration of how to interpret the data.
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/dff8d991-6198-4a55-8dd7-7777796af7a6)
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/1d835bde-457d-4028-94df-ad5f19df2a46)

### Preflight
Before executing the import, Zetkin can present the user with information on what will happen.
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/950efe29-99b3-464b-9e40-708104f6da5b)

### Post-import summary
After the import, Zetkin will summarize how it went
![image](https://github.com/zetkin/app.zetkin.org/assets/550212/6269d04b-4699-4543-9c79-e480deb7adb4)

## Tasks
- [x] New "create" button on people page
- [x] File upload step and data parsing
- [x] Configuration step
- [x] Preflight step
- [x] Post-import summary
