### ISSUE TITLE
User assignments and sign-ups, "My Todo" ✊

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#1617]
## Description
A user should be able to find all the things that they are currently assigned in a single place. This includes call assignments, events that they have signed up for or otherwise been booked on, and tasks.

See epic #1615 for context.

## Estimated size (S, M, L)
I think this issue is medium because the page and it's layout should be very simple, but it requires retrieving data from several different endpoints and presenting it side-by-side. The "tasks" feature has never been implemented in the Activist Portal before.

## Prerequisites
None

## Requirements
- [ ] Build "My todo list" at `/my/todo`
- [ ] List all current call assignments for the user
- [ ] List all upcoming events that the user has signed up for or been booked on
- [ ] List all tasks that the user has been assigned

## Possible implementations
Maybe reuse event components from #1616.

## Design specifications
Design will be developed along with the functionality, but the old Gen2 interface can hopefully be inspiring.

* The design should be mobile-first
* This page will replace the "My actions" and "Call assignments" sections at http://www.dev.zetkin.org/dashboard

**Comment by richardolsson** [comment]
Branch off the base branch called `epic-1615/activist-portal-base` (PR #1623) when working on this at the Code Camp.

**Comment by richardolsson** [comment]
This was implemented in #2425 .
