### ISSUE TITLE
Support Events

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#225]
### Event Pages
These pages can exist in two locations, both as a sub-page of a campaign for an event that belongs to that campaign, and as a sub-page directly on the organization for events that belong to no campaign.

#### Detail Page
WIP - Probably needs own issue

#### Participants Page
WIP - Probably needs own epic issue
* See a list of sign-ups
* Book a sign-up as participant
* See a list of participants
* Add/remove participants

- [ ] Participants list
  - [ ] Add another participant via search
  - [ ] Remove participant
  - [ ] Assign participant as contact person
- [ ] Sign-up list
  - [ ] Click a sign-up to add as participant

#### Other
- [ ] #397
- [ ] #157 

### Non-Event Pages Tasks
- [x] #256
- [ ] #398 

### Open Questions
- How does the "send reminders" functionality look and work. Does this go in the Action Buttons, or on the participants page? This needs a confirmation modal.

**Comment by richardolsson** [comment]
Closing this as events are being revamped in R39.
