### ISSUE TITLE
Divide "filter gallery" into sections

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#361]
Currently the grid of filters is hard to get a proper overview of. This is what it currently looks like

![image](https://user-images.githubusercontent.com/550212/128743812-cda3bddf-0c54-4583-8ada-1f02048a688c.png)

# Proposed new UI features
- [x] Separate lists with headlines (see categorization below).
- [ ] Maybe add a sidebar "table of contents" to jump directly to a category?
- [ ] Maybe add a simple search input in the top right to filter based on label?

# Category breakdown
Separate the many filters into sections, like so:

## "People database" category
* Based on their name, address or other data
* Based on their tags
* Based on custom fields (not yet implemented, see #347)

## "Phone banking" category
* Based on their call history
* Callers (not yet implemented)

## "Campaign activity" category
* Based on their campaign participation
* The most active people

## "Surveys" category
* Based on the options…
* Based on their responses to survey questions (maybe rephrase to clearly indicate that it's for free text questions)
* People who have responded to a survey (maybe rephrase as "submitted a survey")

## "Misc" category
* Another Smart Search query
* People who used Zetkin
* A random selection of people

**Comment by richardolsson** [comment]
This was resolved by #401
