### ISSUE TITLE
Managing sub-organization connections

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#453]
A privileged user should be able to manage a person's connections to sub-organizations.

## Definitions of key terminology
* Sub-organization: an organization which is related to another organization in a tree such that it's their "child". Any organization may have sub-organizations, and they can be any number of levels deep.
* Super-organization: an organization that has sub-organizations. An organization can be a sub-organization to one organization and at the same time be a super-organization when it has sub-organizations of its own.
* Connection: Relationship between a person and an organization. The same person may exist in (have connections to) multiple sub-organizations within the same tree, e.g. a local chapter, district branch and national organization
* Membership: Older (technical) term for what we today usually refer to as Connection

## Target audience
These are the roles that will most likely use this feature:

* Database managers/admins in super-organizations, whose job is to make sure that people are connected to the right sub-organizations (e.g. after moving)

## Requirements (job stories)
Below are job stories that describe the requirements for this feature.

### Need to have
- [x] When I'm inspecting a person, I want to see what sub-organizations they are connected to, so that I can easily spot discrepancies like belonging to two "competing" sectors at once or a geographical branch that does not match their address
- [x] When a person has moved between two geographical chapters below the branch that I manage, I want to be able to remove them from one sub-organization and add them to another, so that the right officials have access to their information
- [x] When a person expresses interest in a certain sector of my organization, I want to be able to add them to that sector's sub-organization, so that their organizers can start working that person
- [x] When a person should be added to a sub-organization, I want to be able to search to find that sub-organization, so that I don't have to go through the entire list of sub-organizations to add them

### Nice to have / known future improvements
- [ ] When a person is connected to a sub-organization, I want to be able to "jump to" their profile page in that sub-organization, to manage that sub-organizations information about the person

## Solution
TBD

## Tasks
TBD

**Comment by richardolsson** [comment]
All need-to-haves were fixed in #566
