### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#454]
Most types of data in Zetkin can be found using the search API. The user should be able to search for a string of text and find (almost) anything, like campaigns, people et c. In a first iteration, being able to find _people_ is enough.

## Definitions of key terminology
* "Search string" refers to any text that can be typed into the search bar and is matched against a number of key strings in the objects being searched, e.g. the name or e-mail address of a person, or the title of a campaign
* "Fuzzy" search refers to the ability of finding something despite spelling discrepancies

## Target audience
These are the roles that will most likely use this feature:

* Organizers looking to find a person's contact information
* Database managers whose main job is to make sure that information is up to date, relevant and clean

## Requirements (job stories)
Below are job stories that describe the requirements for this feature.

### Need to have
- [x] When I need to contact someone in my organizing, I want to be able to search for their name so that I can find their contact information and reach out to them
- [x] When I come to Zetkin to work on something like a campaign, call assignment, survey or view, I want to type in it's name and find a link, so that I can quickly jump to the relevant page
- [ ] When I'm working on something (e.g. a campaign) and need to look up something else for reference, I want to be able to search for that piece of information and see it in context, so that I don't have to move away from what I'm working on
- [x] When I'm searching for something, I want fast feedback on whether my search string will yield relevant results, so that I don't have to wait too long before trying another search string
- [x] When my search yields a large number of different results, I want to be able to narrow it down based on "type" of information, e.g. campaigns, events, people etc, so that I can find what's relevant without having to know exactly what field I'm looking for
- [x] When my search yields two or more identically named matches (e.g. two people with the same name) I want some additional information to be displayed, so that I can tell the matches apart
- [x] When I search for a string, I want to find people that match, so that I can jump to their profile page and continue working

### Nice to have / known future improvements
- [ ] When I search for something that isn't a name (e.g. a phone number, e-mail or membership ID), I want to find people and see the matching piece of information, so that I understand why a person was deemed matching
- [ ] When a match is not an exact match, I want to see how it resembles my search string, so that I can decide whether it's relevant
- [ ] When I search for a string, I want to find data of the following types:
  * Views, so that I can navigate to that view
  * Surveys, so that I can find basic information about the survey like number of submissions, or navigate to the full information
  * Survey submissions, so that I can find a survey filled out by a certain person
  * Campaigns, so that I can find basic information about the campaign or navigate to the full information
  * Call assignments, so that I can find basic information like duration and status, or navigate to the full information
  * Tasks, so that I can find basic information like status and assignee count, or navigate to the full information
  * Cases, so that I can find basic information like status, or navigate to the full information to work on it
  * Smart Search queries by title, so that I can see a list of people matching the query

## Solution
TBD

## Tasks
- [x] #552

**Comment by richardolsson** [comment]
Where does this go?

Here 👇 

![image](https://user-images.githubusercontent.com/550212/151546045-d5d53d89-f357-4895-9a42-ea344a82f107.png)

**Comment by richardolsson** [comment]
Closing this, as it is superseded by new designs and procedures. The remaining ideas in this issue are still valid, but will surely resurface down the line if they map to actual requirements.
