### ISSUE TITLE
Journey instance milestones screen

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#579]
## Description
A user should be able to see all the milestones of a journey instance on a dedicated screen. On that screen it should also be possible to edit the deadlines of milestones, and mark them as complete.

## Relevant Job Stories
* When a case is handed over to me, I want to be able to clearly see the dates of events, so that I don’t miss any limitation deadlines which would cause the case to be thrown out
* When a member shows proof of payment, I want to indicate in the system that the amount has been paid, so that we can stop chasing payment
* When I'm opening a case, I want to complete the preflight checklist so that all necessary information is available to the case worker
* When I have a deadline coming up, I want to be made aware of it so that I never miss a deadline
* When important dates and deadlines change, I want to be able to update them in the system, so that reminders and flags show up at the right time
* When I’m worried that we might be missing deadlines, I want to filter out the relevant upcoming deadlines from all the other information, so that I can clearly see what’s coming up for all cases
* When I've filed a tribunal application, I want to store all important dates, so that they are not missed in the future

## Prerequisites
None

## Requirements
- [x] This should be another tab on the journey instance page called "Milestones"
- [x] At the top should be a progress bar
- [x] A list of all the milestones
  - [x] Title
  - [x] Description (optional)
  - [x] Deadline date picker (editable)
  - [x] Checkbox which (editable)

## Possible implementations
Milestones and their status are retrieved as part of the journey instance.

The editable fields are updated in the API using `PATCH /orgs/{org_id}/journey_instances/{instance_id}/milestones/{milestone_id}` using `completed` and `deadline` date fields.

## Design specifications
The screenshot below shows the interface, but is a bit misleading because it indicates a 20% progress even though no milestones have been checked off.

![image](https://user-images.githubusercontent.com/550212/163341646-c3773819-7aba-4d3c-8986-27935c131a58.png)

## Open questions
None

**Comment by ziggabyte** [comment]
@GemCopeland Am I correct in thinking to make the title text turn grey if completed is checked for visual feedback?

**Comment by richardolsson** [comment]
This is what they look like in Figma, so I don't think they are supposed to change color when done.

![image](https://user-images.githubusercontent.com/550212/167624780-ca170c03-791b-4b34-a718-b4960951cca5.png)

[Figma](https://www.figma.com/file/D4PrAup54f3vS4apqY3M7U/Journeys-MVP?node-id=1427%3A55018)

**Comment by ziggabyte** [comment]
> This is what they look like in Figma, so I don't think they are supposed to change color when done.

Thank you!
