### ISSUE TITLE
Timeline event: Journey milestone

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#587]
## Description
A user should be able to see on the timeline of a journey instance when a milestone was updated.

## Relevant Job Stories
* When I'm covering for someone else during leave, I want to see the full history of the case so that I know where to pick up
* When a case is handed over to me, I want to be able to find all the necessary information, so that I can have a meaningful conversation with the member and not ask the same questions that have already been answered
* When a member reaches out to ask about the status of their case, I want to be able to easily find it so that I can respond without forwarding to someone else

## Prerequisites
Do not start until #584 has been completed

## Requirements
- [x] There should be a summary indicating what happened (one of two things)
  - [x] "[Actor] completed a milestone"
  - [x] "[Actor] marked a milestone as incomplete"
- [x] The details section of the event should include the milestones title

## Possible implementations
Expect the event format to be:

```ts
{
  id: '1650973653871-1',
  type: 'journeyinstance.updatemilestone',
  timestamp: '2022-04-26T15:22:00.000Z',
  actor: {
    id: 1,
    first_name: 'Clara',
    last_name: 'Zetkin',
  },
  target: {
    id: 1,
    title: 'Title of journey instance which can be null',
  },
  details: {
    milestone: {
      id: 1,
      title: 'title of milestone',
    },
    changes: {
      completed: { from: null, to: '2022-04-23T12:10:00.000Z' },
    },
  }
}
```

## Design specifications
<img width="587" alt="image" src="https://user-images.githubusercontent.com/550212/164889995-0a0cc06c-4e9a-463e-bed9-8fe2e3ed5c00.png">

## Open questions
* Some events of this `type` will not be changes to the `completed` field, but to the `deadline` field. Is there any way we can easily render updates to the deadline? We are missing the design for this and won't be getting it before release.

**Comment by lowlandjuju** [comment]
@richardolsson what's the point of this date? { from: null, to: '2022-04-23T12:10:00.000Z' }

**Comment by lowlandjuju** [comment]
@richardolsson the data model here in the "milestone" field is:

```
milestone: {
      id: 1,
      title: 'title of milestone',
    }
```

But in the type it's:

```
export interface ZetkinJourneyMilestone {
  description: string;
  title: string;
}
```

I would assume the      ZetkinJourneyMilestone has an id so should I add it to the type, and should the description field stay or be deleted?

**Comment by lowlandjuju** [comment]
Also, will "changes" ever be plural? If so will it be plural as an object with multiple keys, or an array of  objects?

The latter would be better imo

**Comment by richardolsson** [comment]
> I would assume the ZetkinJourneyMilestone has an id so should I add it to the type, and should the description field stay or be deleted?

Yes, there should be an ID, both in the regular milestone types, and in the inline version. I simply forgot to add it to the types originally created by Ziggi when I hooked up the API. I think it would make sense to add it to the `ZetkinJourneyMilestone` and `ZetkinJourneyMilestoneStatus` types, even though they aren't really relevant here.

In this context the `milestone` is an "inline" version of the milestone model. In the inline object there will not be a description. This follows the same pattern that most inline objects do in the Zetkin API, i.e. objects that are referenced from another object. Compare this to `ZetkinTask` which contains references to campaign and organization using `{ id: number, title: string }` objects rather than full `ZetkinCampaign` or `ZetkinOrganization` objects.

> Also, will "changes" ever be plural? If so will it be plural as an object with multiple keys, or an array of objects? The latter would be better imo

The `changes` pattern is used across all update events, so although it will never be plural in this particular case (where only one field can be updated at a time), it is stil called `changes`.

The way it's currently implemented, updating two fields (`x` and `y`) would yield a `changes` object like this:

```
changes: {
  x: { from: "Old value", to: "New value" },
  y: { from: null, to: "A value that used to be null" },
}
```

This is what I'm referring to in the open question above. Would be curious to hear what you think about how we could potentially render updates to the deadline as well.

**Comment by lowlandjuju** [comment]
In other words: delete "description", add "id"

**Comment by lowlandjuju** [comment]
@richardolsson 
So this requirement "[Actor] marked a milestone as incomplete"

Is this when:

(a) someone decides that a milestone which was marked as "completed", actually isn't complete; so it's a reversion. So then the changes field would be e.g. `completed: { from: '2022-04-23T12:10:00.000Z', to: null },`

OR

(b) something else

**Comment by richardolsson** [comment]
> In other words: delete "description", add "id"

Not really. Nothing should be deleted from the code as it stands. The `description` is still a valid field of the `ZetkinJourneyMilestone` type, but what we're discussing here (the `milestone` field of a particular event's details) is not a `ZetkinJourneyMilestone`. They are not the same types.

> Is this when:
> 
> (a) someone decides that a milestone which was marked as "completed", actually isn't complete; so it's a reversion. So then the changes field would be e.g. completed: { from: '2022-04-23T12:10:00.000Z', to: null },

Yes, that's correct!

**Comment by lowlandjuju** [comment]
Ok, in the interests of clarity can you please fill in the blanks here:

export interface ZetkinJourneyMilestone {
  title: string;
  BLANK
}

export interface ZetkinJourneyMilestoneStatus {
  completed: string | null;
  deadline: string | null;
  title: string;
  BLANK
}

**Comment by richardolsson** [comment]
> Ok, in the interests of clarity can you please fill in the blanks here:

```
export interface ZetkinJourneyMilestone {
id: number;
title: string;
description: string;
}
```

```
export interface ZetkinJourneyMilestoneStatus {
completed: string | null;
deadline: string | null;
title: string;
id: number;
description: string;
}
```

Do note however, that none of the two types above are directly relevant to the task at hand. The event type relevant to this task does not have either of the two types above in it.

> Then the other question, which of the following is true:
>
> (a) "actor" is never null for this update type

This (a) is true for this update type and all other update types right now. In the future that might change, but not in a way that we need to worry about right now.

**Comment by lowlandjuju** [comment]
@richardolsson 
Design proposal for deadline change:

<img width="411" alt="Screenshot 2022-04-26 20 08 34" src="https://user-images.githubusercontent.com/4164774/165364664-2f3de091-2244-411b-8767-85e77466393f.png">

**Comment by richardolsson** [comment]
I think that looks nice @lowlandjuju!
