### ISSUE TITLE
Avoid confusion about milestone deadlines

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#685]
## Description
Users are confused about the deadline field in the milestones tab of journey instances. It's not clear that the date is a deadline, and when the milestone is marked as completed, some users have read the (deadline) date as the date of completion.

## Relevant Job Stories
Not applicable

## Prerequisites
None

## Requirements
- [ ] Rename "add date" label to "due date"
- [ ] Make label always remain on input (not using placeholder)
- [ ] Once milestone is completed, replace with label saying "Completed <N days ago>, was due <due-date>"

## Possible implementations
None

## Design specifications
None

## Open questions
None
