### ISSUE TITLE
Pre-release polishing

### ISSUE THREAD

**Issue by richardolsson** [zetkin/app.zetkin.org#965]
## Description
This task contains a bulk of smaller polishing tasks that would elevate the experience of the release if we can fit them in.

## Sub-tasks
- [x] Keyboard toggling `local_bool` cells
- [x] Keyboard toggling `person_tag` cells
- [x] Enter `local_text` edit mode using keyboard (autofocus the input)
- [x] Tweak typography of label that shows up when picking a free text question in the "Survey response" choice
- [x] Center icon in multi-column choice card
- [ ] Keyboard selecting person for `local_person` cells
- [ ] Add little arrow to view poppers (`SurveySubmissionPreview` and `PersonCell`)
- [x] Enforce order of combo choice columns, either using an `async` loop or an RPC endpoint
- [ ] Reload view row after changing tags (as that could also affect smart searches)
- [x] Handle unsupported column types (ignore them entirely be removing them from store as they load?)
- [x] Restrict view editing when `accessLevel` is `readonly`
- [x] Make sure sorting and filtering is working as expected for all column types
- [ ] Error when deleting columns as mentioned by Ziggi in #969 review

## Design specifications
None

## Open questions
None

**Comment by richardolsson** [comment]
I'm closing this with four unfinished tasks, with the following motivations:

* Keyboard selection for `local_person` is not prioritized and something similar will be implemented in surveys (R38) anyway
* Adding little arrows becomes less important when we re-implement the person selector popper in R38
* Invalidating/reloading view rows would be nice but requires a fair bit of changes, no time right now
* I can't reproduce the error described by @ziggabyte in #969
